on: [push, pull_request]

name: Continuous integration

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: rustfmt
        run: cargo fmt --all -- --check
        working-directory: ./bevy_baseview_plugin/

      - name: Install baseview dependencies
        run: |
          sudo apt update
          sudo apt install libx11-xcb-dev libxcb-dri2-0-dev libgl1-mesa-dev libxcb-icccm4-dev libxcursor-dev libasound2-dev libudev-dev

      - name: cargo check
        run: cargo check
        working-directory: ./bevy_baseview_plugin/

      - name: clippy
        run: cargo clippy
        working-directory: ./bevy_baseview_plugin/

      - name: cargo test
        run: cargo test
        working-directory: ./bevy_baseview_plugin/
